import type { Content, Genre, Plan, CastMember, User, Device } from '@/types';

export const genres: Genre[] = [
  { id: 'g1', name: 'Action' },
  { id: 'g2', name: 'Sci-Fi' },
  { id: 'g3', name: 'Drama' },
  { id: 'g4', name: 'Thriller' },
  { id: 'g5', name: 'Horror' },
  { id: 'g6', name: 'Romance' },
  { id: 'g7', name: 'Fantasy' },
  { id: 'g8', name: 'Crime' },
  { id: 'g9', name: 'Mystery' },
  { id: 'g10', name: 'Adventure' },
  { id: 'g11', name: 'Comedy' },
  { id: 'g12', name: 'Documentary' },
];

export const castMembers: CastMember[] = [
  { id: 'c1', name: 'Marcus Vale', character: 'Detective Cross', photo: 'https://images.pexels.com/photos/29433729/pexels-photo-29433729.png?auto=compress&cs=tinysrgb&h=400&w=300' },
  { id: 'c2', name: 'Elena Roshan', character: 'Agent Vale', photo: 'https://images.pexels.com/photos/15649980/pexels-photo-15649980.jpeg?auto=compress&cs=tinysrgb&h=400&w=300' },
  { id: 'c3', name: 'Dario Kane', character: 'The Architect', photo: 'https://images.pexels.com/photos/35964821/pexels-photo-35964821.jpeg?auto=compress&cs=tinysrgb&h=400&w=300' },
  { id: 'c4', name: 'Sofia Lin', character: 'Dr. Mercer', photo: 'https://images.pexels.com/photos/21316136/pexels-photo-21316136.jpeg?auto=compress&cs=tinysrgb&h=400&w=300' },
  { id: 'c5', name: 'Julian Frost', character: 'Commander', photo: 'https://images.pexels.com/photos/22738088/pexels-photo-22738088.jpeg?auto=compress&cs=tinysrgb&h=400&w=300' },
  { id: 'c6', name: 'Naya Brooks', character: 'The Oracle', photo: 'https://images.pexels.com/photos/34622355/pexels-photo-34622355.jpeg?auto=compress&cs=tinysrgb&h=400&w=300' },
];

const B = (url: string, w = 1600) => `${url}&w=${w}`;
const P = (url: string, w = 600) => `${url}&w=${w}`;

export const content: Content[] = [
  {
    id: 'm1',
    title: 'Shadow Protocol',
    description: 'When a covert intelligence operation goes dark, a lone operative must navigate a labyrinth of betrayal to uncover a conspiracy that reaches the highest levels of power. Time is running out, and trust is a luxury she cannot afford.',
    type: 'movie',
    posterUrl: P('https://images.pexels.com/photos/23384428/pexels-photo-23384428.jpeg?auto=compress&cs=tinysrgb&h=900'),
    backdropUrl: B('https://images.pexels.com/photos/23384428/pexels-photo-23384428.jpeg?auto=compress&cs=tinysrgb&h=900'),
    genres: ['g1', 'g4', 'g8'],
    cast: ['c1', 'c2', 'c3'],
    ageRating: 'R',
    year: 2024,
    duration: 7340,
    averageRating: 4.6,
    ratingsCount: 12840,
    viewsCount: 892000,
    featured: true,
    trending: true,
    isNew: true,
  },
  {
    id: 's1',
    title: 'Neon Horizon',
    description: 'In a sprawling megacity where memories can be traded like currency, a rogue data broker discovers a secret that could rewrite the fabric of reality itself. A breathtaking cyberpunk saga of identity, power, and the ghosts we carry inside.',
    type: 'series',
    posterUrl: P('https://images.pexels.com/photos/8107900/pexels-photo-8107900.jpeg?auto=compress&cs=tinysrgb&h=900'),
    backdropUrl: B('https://images.pexels.com/photos/8107900/pexels-photo-8107900.jpeg?auto=compress&cs=tinysrgb&h=900'),
    genres: ['g2', 'g4', 'g7'],
    cast: ['c2', 'c4', 'c6'],
    ageRating: 'TV-MA',
    year: 2024,
    duration: 0,
    averageRating: 4.8,
    ratingsCount: 24310,
    viewsCount: 1240000,
    featured: true,
    trending: true,
    isNew: true,
    seasons: [
      {
        id: 's1-s1',
        seasonNumber: 1,
        title: 'Season 1',
        episodes: [
          { id: 's1-s1-e1', episodeNumber: 1, title: 'Ghost in the Signal', description: 'A data broker stumbles upon a memory that shouldn\'t exist.', duration: 3120, thumbnail: 'https://images.pexels.com/photos/8107980/pexels-photo-8107980.jpeg?auto=compress&cs=tinysrgb&h=400', videoUrl: '' },
          { id: 's1-s1-e2', episodeNumber: 2, title: 'Black Market Dreams', description: 'Naya goes underground to trace the memory\'s origin.', duration: 2980, thumbnail: 'https://images.pexels.com/photos/8107954/pexels-photo-8107954.jpeg?auto=compress&cs=tinysrgb&h=400', videoUrl: '' },
          { id: 's1-s1-e3', episodeNumber: 3, title: 'The Architect\'s Game', description: 'A mysterious figure offers Naya a dangerous bargain.', duration: 3240, thumbnail: 'https://images.pexels.com/photos/8107896/pexels-photo-8107896.jpeg?auto=compress&cs=tinysrgb&h=400', videoUrl: '' },
        ],
      },
      {
        id: 's1-s2',
        seasonNumber: 2,
        title: 'Season 2',
        episodes: [
          { id: 's1-s2-e1', episodeNumber: 1, title: 'Fractured Light', description: 'The city reels from the events of the season one finale.', duration: 3360, thumbnail: 'https://images.pexels.com/photos/8108517/pexels-photo-8108517.jpeg?auto=compress&cs=tinysrgb&h=400', videoUrl: '' },
          { id: 's1-s2-e2', episodeNumber: 2, title: 'Echoes', description: 'Old memories resurface with deadly consequences.', duration: 3100, thumbnail: 'https://images.pexels.com/photos/8108481/pexels-photo-8108481.jpeg?auto=compress&cs=tinysrgb&h=400', videoUrl: '' },
        ],
      },
    ],
  },
  {
    id: 'm2',
    title: 'The Last Outpost',
    description: 'On the edge of known space, a remote colony fights for survival against an ancient force that awakens beneath the ice. A sweeping sci-fi epic about humanity\'s last stand.',
    type: 'movie',
    posterUrl: P('https://images.pexels.com/photos/7671976/pexels-photo-7671976.jpeg?auto=compress&cs=tinysrgb&h=900'),
    backdropUrl: B('https://images.pexels.com/photos/7671976/pexels-photo-7671976.jpeg?auto=compress&cs=tinysrgb&h=900'),
    genres: ['g2', 'g10', 'g3'],
    cast: ['c5', 'c4', 'c1'],
    ageRating: 'PG-13',
    year: 2023,
    duration: 8120,
    averageRating: 4.3,
    ratingsCount: 8900,
    viewsCount: 540000,
    trending: true,
  },
  {
    id: 'm3',
    title: 'Crimson Veil',
    description: 'A paranormal investigator returns to her hometown to uncover the truth behind a series of disappearances that echo a childhood trauma she\'s tried to forget.',
    type: 'movie',
    posterUrl: P('https://images.pexels.com/photos/14648586/pexels-photo-14648586.jpeg?auto=compress&cs=tinysrgb&h=900'),
    backdropUrl: B('https://images.pexels.com/photos/14648586/pexels-photo-14648586.jpeg?auto=compress&cs=tinysrgb&h=900'),
    genres: ['g5', 'g9', 'g4'],
    cast: ['c6', 'c2', 'c4'],
    ageRating: 'R',
    year: 2024,
    duration: 6240,
    averageRating: 4.1,
    ratingsCount: 6700,
    viewsCount: 410000,
    isNew: true,
  },
  {
    id: 's2',
    title: 'Iron City Blues',
    description: 'A hard-boiled detective with a haunted past navigates the corrupt underbelly of a steel-town empire, where every ally is a potential enemy and every case cuts too close to home.',
    type: 'series',
    posterUrl: P('https://images.pexels.com/photos/32891033/pexels-photo-32891033.jpeg?auto=compress&cs=tinysrgb&h=900'),
    backdropUrl: B('https://images.pexels.com/photos/32891033/pexels-photo-32891033.jpeg?auto=compress&cs=tinysrgb&h=900'),
    genres: ['g8', 'g3', 'g4'],
    cast: ['c1', 'c3', 'c5'],
    ageRating: 'TV-MA',
    year: 2023,
    duration: 0,
    averageRating: 4.5,
    ratingsCount: 15600,
    viewsCount: 720000,
    trending: true,
    seasons: [
      {
        id: 's2-s1',
        seasonNumber: 1,
        title: 'Season 1',
        episodes: [
          { id: 's2-s1-e1', episodeNumber: 1, title: 'Pilot', description: 'Detective Cross catches a case that reopens old wounds.', duration: 3400, thumbnail: 'https://images.pexels.com/photos/23384407/pexels-photo-23384407.jpeg?auto=compress&cs=tinysrgb&h=400', videoUrl: '' },
          { id: 's2-s1-e2', episodeNumber: 2, title: 'The Mill', description: 'A body at the steel mill pulls Cross deeper into the city\'s secrets.', duration: 2960, thumbnail: 'https://images.pexels.com/photos/23384400/pexels-photo-23384400.jpeg?auto=compress&cs=tinysrgb&h=400', videoUrl: '' },
        ],
      },
    ],
  },
  {
    id: 'm4',
    title: 'Golden Hour',
    description: 'Two strangers meet on the last train of the night and spend a single luminous evening wandering a city that feels like it was made for them. A tender romance about fleeting connection.',
    type: 'movie',
    posterUrl: P('https://images.pexels.com/photos/1024961/pexels-photo-1024961.jpeg?auto=compress&cs=tinysrgb&h=900'),
    backdropUrl: B('https://images.pexels.com/photos/1024961/pexels-photo-1024961.jpeg?auto=compress&cs=tinysrgb&h=900'),
    genres: ['g6', 'g3'],
    cast: ['c2', 'c5'],
    ageRating: 'PG-13',
    year: 2024,
    duration: 5400,
    averageRating: 4.4,
    ratingsCount: 9200,
    viewsCount: 380000,
    isNew: true,
  },
  {
    id: 'm5',
    title: 'The Hollow Wood',
    description: 'A family inherits a remote estate surrounded by ancient forest, only to discover the woods have been keeping a centuries-old covenant — and they are now part of it.',
    type: 'movie',
    posterUrl: P('https://images.pexels.com/photos/217660/pexels-photo-217660.jpeg?auto=compress&cs=tinysrgb&h=900'),
    backdropUrl: B('https://images.pexels.com/photos/217660/pexels-photo-217660.jpeg?auto=compress&cs=tinysrgb&h=900'),
    genres: ['g5', 'g7', 'g9'],
    cast: ['c6', 'c4', 'c1'],
    ageRating: 'R',
    year: 2023,
    duration: 6800,
    averageRating: 3.9,
    ratingsCount: 5400,
    viewsCount: 290000,
  },
  {
    id: 's3',
    title: 'Summit of Kings',
    description: 'Rival dynasties wage a generations-long war for control of a mountain kingdom, where alliances are forged in blood and broken by ambition. An epic fantasy saga.',
    type: 'series',
    posterUrl: P('https://images.pexels.com/photos/1278540/pexels-photo-1278540.jpeg?auto=compress&cs=tinysrgb&h=900'),
    backdropUrl: B('https://images.pexels.com/photos/1278540/pexels-photo-1278540.jpeg?auto=compress&cs=tinysrgb&h=900'),
    genres: ['g7', 'g3', 'g10'],
    cast: ['c3', 'c5', 'c1', 'c6'],
    ageRating: 'TV-14',
    year: 2023,
    duration: 0,
    averageRating: 4.7,
    ratingsCount: 31000,
    viewsCount: 1600000,
    trending: true,
    seasons: [
      {
        id: 's3-s1',
        seasonNumber: 1,
        title: 'Season 1',
        episodes: [
          { id: 's3-s1-e1', episodeNumber: 1, title: 'The Crown\'s Weight', description: 'A king\'s sudden death throws the realm into chaos.', duration: 3600, thumbnail: 'https://images.pexels.com/photos/13695383/pexels-photo-13695383.jpeg?auto=compress&cs=tinysrgb&h=400', videoUrl: '' },
          { id: 's3-s1-e2', episodeNumber: 2, title: 'Oaths in Stone', description: 'The rival houses make their moves.', duration: 3500, thumbnail: 'https://images.pexels.com/photos/2387966/pexels-photo-2387966.jpeg?auto=compress&cs=tinysrgb&h=400', videoUrl: '' },
          { id: 's3-s1-e3', episodeNumber: 3, title: 'The Long Climb', description: 'An expedition sets out for the summit.', duration: 3400, thumbnail: 'https://images.pexels.com/photos/720240/pexels-photo-720240.jpeg?auto=compress&cs=tinysrgb&h=400', videoUrl: '' },
        ],
      },
    ],
  },
  {
    id: 'm6',
    title: 'Code Red',
    description: 'An elite counter-terrorism unit races against time to stop a coordinated attack on the world\'s financial centers. Adrenaline-fueled action from start to finish.',
    type: 'movie',
    posterUrl: P('https://images.pexels.com/photos/8683446/pexels-photo-8683446.jpeg?auto=compress&cs=tinysrgb&h=900'),
    backdropUrl: B('https://images.pexels.com/photos/8683446/pexels-photo-8683446.jpeg?auto=compress&cs=tinysrgb&h=900'),
    genres: ['g1', 'g4'],
    cast: ['c1', 'c5', 'c3'],
    ageRating: 'R',
    year: 2024,
    duration: 6900,
    averageRating: 4.0,
    ratingsCount: 7800,
    viewsCount: 460000,
    isNew: true,
  },
  {
    id: 'm7',
    title: 'After the Fall',
    description: 'In the ruins of a collapsed civilization, a former soldier escorts a child rumored to hold the key to humanity\'s future across a hostile wasteland.',
    type: 'movie',
    posterUrl: P('https://images.pexels.com/photos/19949819/pexels-photo-19949819.jpeg?auto=compress&cs=tinysrgb&h=900'),
    backdropUrl: B('https://images.pexels.com/photos/19949819/pexels-photo-19949819.jpeg?auto=compress&cs=tinysrgb&h=900'),
    genres: ['g1', 'g7', 'g3'],
    cast: ['c5', 'c6', 'c4'],
    ageRating: 'PG-13',
    year: 2023,
    duration: 7600,
    averageRating: 4.2,
    ratingsCount: 11200,
    viewsCount: 680000,
  },
  {
    id: 's4',
    title: 'Midnight Circuit',
    description: 'Underground street racers uncover a conspiracy when their races become the testing ground for a shadowy tech conglomerate\'s autonomous weapon program.',
    type: 'series',
    posterUrl: P('https://images.pexels.com/photos/8718381/pexels-photo-8718381.jpeg?auto=compress&cs=tinysrgb&h=900'),
    backdropUrl: B('https://images.pexels.com/photos/8718381/pexels-photo-8718381.jpeg?auto=compress&cs=tinysrgb&h=900'),
    genres: ['g1', 'g4', 'g8'],
    cast: ['c3', 'c2', 'c1'],
    ageRating: 'TV-14',
    year: 2024,
    duration: 0,
    averageRating: 4.1,
    ratingsCount: 6300,
    viewsCount: 350000,
    isNew: true,
    seasons: [
      {
        id: 's4-s1',
        seasonNumber: 1,
        title: 'Season 1',
        episodes: [
          { id: 's4-s1-e1', episodeNumber: 1, title: 'Green Light', description: 'A rookie racer gets recruited into the elite circuit.', duration: 2800, thumbnail: 'https://images.pexels.com/photos/11794336/pexels-photo-11794336.jpeg?auto=compress&cs=tinysrgb&h=400', videoUrl: '' },
          { id: 's4-s1-e2', episodeNumber: 2, title: 'Blind Turns', description: 'The first race reveals something is very wrong.', duration: 2900, thumbnail: 'https://images.pexels.com/photos/30937521/pexels-photo-30937521.jpeg?auto=compress&cs=tinysrgb&h=400', videoUrl: '' },
        ],
      },
    ],
  },
  {
    id: 'm8',
    title: 'Letters from the Sea',
    description: 'A lighthouse keeper discovers a trunk of undelivered letters from a century past, each one a window into a love story that never reached its destination.',
    type: 'movie',
    posterUrl: P('https://images.pexels.com/photos/7981701/pexels-photo-7981701.jpeg?auto=compress&cs=tinysrgb&h=900'),
    backdropUrl: B('https://images.pexels.com/photos/7981701/pexels-photo-7981701.jpeg?auto=compress&cs=tinysrgb&h=900'),
    genres: ['g6', 'g3', 'g12'],
    cast: ['c2', 'c6'],
    ageRating: 'PG',
    year: 2023,
    duration: 5800,
    averageRating: 4.5,
    ratingsCount: 8100,
    viewsCount: 320000,
  },
  {
    id: 'm9',
    title: 'The Void Between',
    description: 'Astronauts on a deep-space mission lose contact with Earth and must confront the possibility that they are no longer alone — and no longer themselves.',
    type: 'movie',
    posterUrl: P('https://images.pexels.com/photos/29146231/pexels-photo-29146231.jpeg?auto=compress&cs=tinysrgb&h=900'),
    backdropUrl: B('https://images.pexels.com/photos/29146231/pexels-photo-29146231.jpeg?auto=compress&cs=tinysrgb&h=900'),
    genres: ['g2', 'g5', 'g9'],
    cast: ['c4', 'c5', 'c6'],
    ageRating: 'PG-13',
    year: 2024,
    duration: 7200,
    averageRating: 4.3,
    ratingsCount: 9400,
    viewsCount: 510000,
    isNew: true,
    trending: true,
  },
  {
    id: 'm10',
    title: 'Concrete Empire',
    description: 'A young architect rises through the ranks of a ruthless real estate dynasty, but the higher she climbs, the more she must sacrifice to stay on top.',
    type: 'movie',
    posterUrl: P('https://images.pexels.com/photos/793430/pexels-photo-793430.jpeg?auto=compress&cs=tinysrgb&h=900'),
    backdropUrl: B('https://images.pexels.com/photos/793430/pexels-photo-793430.jpeg?auto=compress&cs=tinysrgb&h=900'),
    genres: ['g3', 'g8'],
    cast: ['c2', 'c3', 'c4'],
    ageRating: 'R',
    year: 2023,
    duration: 6600,
    averageRating: 4.0,
    ratingsCount: 4900,
    viewsCount: 240000,
  },
  {
    id: 's5',
    title: 'The Whispering Pines',
    description: 'A small-town sheriff investigates a series of bizarre occurrences in a forest community where the trees seem to remember everything — and everyone.',
    type: 'series',
    posterUrl: P('https://images.pexels.com/photos/289367/pexels-photo-289367.jpeg?auto=compress&cs=tinysrgb&h=900'),
    backdropUrl: B('https://images.pexels.com/photos/289367/pexels-photo-289367.jpeg?auto=compress&cs=tinysrgb&h=900'),
    genres: ['g5', 'g9', 'g3'],
    cast: ['c1', 'c6', 'c4'],
    ageRating: 'TV-14',
    year: 2023,
    duration: 0,
    averageRating: 4.2,
    ratingsCount: 7100,
    viewsCount: 430000,
    seasons: [
      {
        id: 's5-s1',
        seasonNumber: 1,
        title: 'Season 1',
        episodes: [
          { id: 's5-s1-e1', episodeNumber: 1, title: 'The First Missing', description: 'A hiker vanishes on a well-marked trail.', duration: 3100, thumbnail: 'https://images.pexels.com/photos/10040325/pexels-photo-10040325.jpeg?auto=compress&cs=tinysrgb&h=400', videoUrl: '' },
          { id: 's5-s1-e2', episodeNumber: 2, title: 'Roots', description: 'The town\'s oldest family reveals a dangerous secret.', duration: 3000, thumbnail: 'https://images.pexels.com/photos/11640401/pexels-photo-11640401.jpeg?auto=compress&cs=tinysrgb&h=400', videoUrl: '' },
        ],
      },
    ],
  },
  {
    id: 'm11',
    title: 'Velocity',
    description: 'A getaway driver with a perfect record takes one last job that turns into a relentless night chase across a city that never sleeps.',
    type: 'movie',
    posterUrl: P('https://images.pexels.com/photos/14389542/pexels-photo-14389542.png?auto=compress&cs=tinysrgb&h=900'),
    backdropUrl: B('https://images.pexels.com/photos/14389542/pexels-photo-14389542.png?auto=compress&cs=tinysrgb&h=900'),
    genres: ['g1', 'g4', 'g8'],
    cast: ['c3', 'c1', 'c2'],
    ageRating: 'R',
    year: 2024,
    duration: 5900,
    averageRating: 3.8,
    ratingsCount: 4200,
    viewsCount: 210000,
    isNew: true,
  },
  {
    id: 'm12',
    title: 'Aurora',
    description: 'A solar physicist races to convince a skeptical world that a catastrophic solar event is imminent, while grappling with her own fading memory.',
    type: 'movie',
    posterUrl: P('https://images.pexels.com/photos/18337644/pexels-photo-18337644.jpeg?auto=compress&cs=tinysrgb&h=900'),
    backdropUrl: B('https://images.pexels.com/photos/18337644/pexels-photo-18337644.jpeg?auto=compress&cs=tinysrgb&h=900'),
    genres: ['g2', 'g3', 'g12'],
    cast: ['c4', 'c6', 'c5'],
    ageRating: 'PG-13',
    year: 2023,
    duration: 6400,
    averageRating: 4.4,
    ratingsCount: 8800,
    viewsCount: 470000,
    trending: true,
  },
];

export const plans: Plan[] = [
  {
    id: 'p1',
    name: 'Basic',
    price: 8.99,
    quality: 'Good',
    resolution: '720p',
    maxDevices: 1,
    maxProfiles: 2,
    moviesLimit: 5,
    seriesLimit: 3,
    description: 'Watch on 1 device at a time in HD. Perfect for solo viewers.',
  },
  {
    id: 'p2',
    name: 'Standard',
    price: 13.99,
    quality: 'Great',
    resolution: '1080p',
    maxDevices: 2,
    maxProfiles: 4,
    moviesLimit: 10,
    seriesLimit: 6,
    description: 'Watch on 2 devices at a time in Full HD. Great for couples.',
    highlighted: true,
  },
  {
    id: 'p3',
    name: 'Premium',
    price: 17.99,
    quality: 'Best',
    resolution: '4K + HDR',
    maxDevices: 4,
    maxProfiles: 6,
    moviesLimit: 0,
    seriesLimit: 0,
    description: 'Watch on 4 devices at a time in Ultra HD. The full experience.',
  },
];

export const mockUser: User = {
  id: 'u1',
  name: 'Alex Carter',
  email: 'alex.carter@email.com',
  role: 'user',
  profiles: [
    { id: 'pr1', name: 'Alex', avatar: '', isPrimary: true, isKids: false, hasPin: false, color: '#ff3b2f' },
    { id: 'pr2', name: 'Sam', avatar: '', isPrimary: false, isKids: false, hasPin: true, color: '#3b82f6' },
    { id: 'pr3', name: 'Kids', avatar: '', isPrimary: false, isKids: true, hasPin: false, color: '#22c55e' },
  ],
  subscription: {
    id: 'sub1',
    planId: 'p2',
    status: 'active',
    startedAt: '2024-01-15T00:00:00Z',
    renewsAt: '2025-09-15T00:00:00Z',
  },
};

export const mockDevices: Device[] = [
  { id: 'd1', name: 'MacBook Pro — Chrome', type: 'laptop', lastActive: '2025-08-01T10:30:00Z', location: 'San Francisco, CA', current: true },
  { id: 'd2', name: 'iPhone 15 Pro', type: 'mobile', lastActive: '2025-07-30T22:15:00Z', location: 'San Francisco, CA' },
  { id: 'd3', name: 'Living Room TV', type: 'tv', lastActive: '2025-07-28T19:45:00Z', location: 'San Francisco, CA' },
  { id: 'd4', name: 'iPad Air', type: 'tablet', lastActive: '2025-07-20T08:00:00Z', location: 'New York, NY' },
];

export const avatarColors = [
  '#ff3b2f', '#3b82f6', '#22c55e', '#f59e0b',
  '#ec4899', '#8b5cf6', '#06b6d4', '#f97316',
];
